### PR TITLE
Remove need for root privileges

### PR DESCRIPTION
**Pull request by frostworx**
A PR for removing the need for root privileges like suggested in #3

### CODE REVIEW

**Comment by chuck-flowers** [comment]
Everything looks good. Can you just update the makefile to add and remove the lines that create the cache directory. Once that is done, I'll test and accept the pull request.

**Comment by frostworx** [comment]
A makefile should not create or delete any user files, so it is save to simply remove the two `/var/local/` lines

**Comment by frostworx** [comment]
the makefile could need some tuning in general. please wait a min :)

**Comment by frostworx** [comment]
works for me

**Comment by chuck-flowers** [comment]
Works for me as well. Merging into master

**Comment by frostworx** [comment]
No problem

**Pull request merged**
